### ISSUE TITLE
Remove "Write access to code" permission

### ISSUE THREAD

**Issue by nicolasrouanne** [dkhmelenko/autoapproval#5]
I see [your GitHub app](https://github.com/apps/autoapproval) **requires _Write access to code_**. Is this mandatory? 
Since you are _"only" approving pull requests_, I would tend think it's not 🤔 .

<img width="427" alt="Screenshot 2019-06-24 at 11 24 41" src="https://user-images.githubusercontent.com/12157019/60007584-dfff4f00-9672-11e9-907d-7eddc47bc290.png">

**Comment by dkhmelenko** [comment]
Thanks for reporting that. This is a valid point. I will revise it and update it.
I will let you know once it's done.

**Comment by dkhmelenko** [comment]
I checked permission and in order to guarantee the normal work of this app, it requires to have Write permissions.

You can read about permissions and approving PRs here https://help.github.com/en/articles/about-pull-request-reviews#required-reviews

```
Repository administrators can require that all pull requests receive a specific number of approving reviews from people with write or admin permissions in the repository or from a designated code owner before they're merged into a protected branch.

...

You won't be able to merge your pull request until the required number of reviewers with write or admin permissions in the repository approve your pull request's changes in their review.
```

**Comment by nicolasrouanne** [comment]
Hum, thats totally right. I guess there's no way around it.
Thanks for looking into it anyway 👌
