### ISSUE TITLE
Dealing with rebased branches

### ISSUE THREAD

**Issue by StephanBijzitter** [dkhmelenko/autoapproval#7]
> If PR already contains all labels from apply_labels config, it will not be approved assuming that it was already approved.

Because of this behaviour, rebasing a branch results in the branch not being approved anymore, while still having the label.

Would you accept a pull request that changes this?

**Comment by StephanBijzitter** [comment]
Ah, just saw that the code only does this when `labelsToAdd` contains one or more entries. So I guess applying no labels would give me the results I'm looking for. Perhaps then a documentation change would be more than enough :-)

**Comment by dkhmelenko** [comment]
Thanks for your PR 👍 

Can you please provide a better use case for the problem? I didn't really understand this sentence.

```
Because of this behaviour, rebasing a branch results in the branch not being approved anymore, while still having the label.
```

**Comment by StephanBijzitter** [comment]
Sure!

So I use Dependabot and it creates a several pull requests at the same time. Autoapproval approves all those pull requests, and so whichever pull request finishes the build process first is merged automatically by Dependabot.

However, after merging that first pull request, all other pull requests are updated with master through rebasing, which removes all reviews from the pull requests.

Dependabot is then unable to merge, because there's no approval anymore and Autoapproval is not approving the updated pull request, so then I have to manually approve it.

**Comment by dkhmelenko** [comment]
Thanks for your explanation! 👍 
This is a valid concern. But I doubt that would work because if PR contains the labels of the approved PR, it will not be approved one more time. Being assumed the following:
- if PR contains the labels of the approved PR it will be considered as already approved.

**Comment by dkhmelenko** [comment]
I know that if you update the branch from GitHub interface, it will not reset the review. Maybe you can consider that?
Another thing which could work for you is removing the label of the approved PR, so that it could be approved one more time.
