### ISSUE TITLE
Service down?

### ISSUE THREAD

**Issue by TomerFi** [dkhmelenko/autoapproval#744]
Hey

Thanks for this cool app!
It looks like it stopped responding a couple of day ago.

**Comment by dkhmelenko** [comment]
Hi! Sorry for that!
It's because Heroku has shut down their free hosting recently. I didn't have time to find new free hosting. If you have any ideas, please share.

I should be able to fix this issue probably in the next few days.

**Comment by dkhmelenko** [comment]
The application is running now on GitHub action.
Add the GitHub Action configuration to your project from the Readme https://github.com/dkhmelenko/autoapproval#setup

Let me know if it works for you

**Comment by TomerFi** [comment]
Actually, I prefer an app for this operation.
Thank you very much for keeping this service up for as long as you did.

**Comment by dkhmelenko** [comment]
Sorry about that, it's hard to find a free alternative that is good as Heroku.

But, this GitHub Action is one way to host the application. In fact, the application remains as is, it's only hosted on GitHub through GitHub Action.

If you still prefer to use the application as before, you can try to host it locally and it will work for you.
